### ISSUE TITLE
mistake in README.md installation commands

### ISSUE THREAD

**Issue by swapnilDCIPL** [DvdMgr/lorawan#17]
In "installing dependencies" section of Ubuntu
Instead on "sudo apt-get install"
it is "sudo apt install"

**Comment by DvdMgr** [comment]
Does it give you an error if you use apt-get?

As I understand it, apt is more 'human-friendly', while apt-get is more 'low-level', however apt-get should still work correctly. Let me know!

**Comment by DvdMgr** [comment]
Closing as there is no update and the issue seems trivial.
