### ISSUE TITLE
./waf build error

### ISSUE THREAD

**Issue by shikharoo7** [DvdMgr/lorawan#20]
## Expected Behavior
lorawan modules should get configured

## Actual Behavior
Could not find a task generator for the name 'ns3-lorawan-master'
![screenshot 2018-04-24 15 05 43](https://user-images.githubusercontent.com/12771409/39179300-99511688-47d1-11e8-9d4b-6ca7a64378af.png)

## Specifications

  - ns-3 version: 3.28
  - lorawan module version: 
  - Platform: Linux Mint 18.3
  - Compiler: Python 3.6.5, gcc 7.2.0

**Comment by DvdMgr** [comment]
Hi!
Is the folder containing the module in the src directory named lorawan?

**Comment by FENGFEINI** [comment]
I also had the same problem, how can I solve it?

**Comment by FENGFEINI** [comment]
file:///home/ffn/Desktop/Screenshot%20-%2004252018%20-%2009:19:18%20AM.png

**Comment by FENGFEINI** [comment]
The following figure is the directory
file:///home/ffn/Desktop/Screenshot%20-%2004252018%20-%2009:19:18%20AM.png

**Comment by FENGFEINI** [comment]
/home/ffn/Downloads/Screenshot - 04252018 - 10:08:02 AM.png

**Comment by FENGFEINI** [comment]
Sorry, I didn't upload screenshots. I still have a question of which version of ns-3 I need to install for using this  lora module.

**Comment by DvdMgr** [comment]
ns-3.27 should be fine!

Anyway, make sure the name of the module folder in src is lorawan, we had a similar discussion on the repo’s gitter chat!

**Comment by shikharoo7** [comment]
yup, that was the problem.
The folder was named as 'lorawan-master' and changing it to 'lorawan' solved the issue.
Thanks!
